import 'package:get/get.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar': {
      '1': 'اختر اللغة',
      '2': 'اختر المنتج',
      '3': ' لدينا أكثر من 100 ألف منتج، اختر \n  منتجك  من  متجرنا',
      '4': 'سهل وآمن للشراء',
      '5': 'يمكنك الدفع كاش أو \n من خلال بوابات الدفع الإلكترونية',
      '6': 'تتبع طلبك',
      '7': 'يمكنك تتبع طلبك في كل مرحلة \n وبشكل مباشر من خلال الخريطة',
      '8': 'متابعة',
      '9': 'تسجيل الدخول',
      '10': 'أهلاً بك،',
      '11':
      'يمكنك تسجيل الدخول من خلال البريد الإلكتروني أو من خلال حسابات وسائل التواصل الاجتماعي',
      '12': 'ادخل البريد الالكتروني',
      '13': 'ادخل كلمة المرور',
      '14': 'هل نسيت كلمة المرور؟',
      '15': 'تسجيل الدخول',
      '16': 'ليس لديك حساب؟ ',
      '17': 'إنشاء حساب',
      '18': 'البريد الإلكتروني',
      '19': 'كلمة المرور',
      '20': 'اسم المستخدم',
      '21': 'رقم الهاتف',
      '22': 'ادخل رقم الهاتف',
      '23': 'ادخل اسم المستخدم',
      '24':
      'إنشاء حساب من خلال البريد أو من خلال حسابات وسائل التواصل الاجتماعي',
      '25': ' لديك حساب؟ ',
      '26': 'تسجيل الدخول',
      '27': 'فحص البريد الالكتروني',
      '28': 'تم إنشاء حسابك بنجاح!',
      '29': 'الرجاء إدخال عنوان البريد الإلكتروني المسجل مسبقاً لتلقي رمز التحقق',
      '30': 'فحص',
      '31': 'الذهاب لتسجيل الدخول',
      '32': 'نجاح!',
      '33': 'حفظ',
      '34': 'الرجاء إدخال كلمة المرور الجديدة',
      '35': 'كلمة المرور الجديدة',
      '36': 'تم إعادة تعيين كلمة المرور بنجاح!',
      '37': 'تهانينا!',
      '38': 'تم التسجيل بنجاح!',
      '39' : 'رمز التحقق',
      '40' : 'تم إرسال رمز التحقق',
      '41' : 'الرجاء إدخال الرمز المكون من 6 أرقام الذي تم إرساله إلى',
      '42' : 'نسيت كلمة المرور',
      '43' : 'إعادة تعيين كلمة المرور',
      '44' : 'اختر كلمة مرور قوية مؤلفة من حروف وأرقام ورموز',
      '45' : 'تأكيد كلمة المرور',
      '46' : 'أعد إدخال كلمة المرور الجديدة',
    },
    'en': {
      '1': 'Choose Language',
      '2': 'Choose Products',
      '3':
      'We Have over 100k Products, Choose \n Your Product From  Our \n E-commerce Shop',
      '4': 'Easy & Safe Payment',
      '5': 'You can pay in cash \n or through E-payment gateways',
      '6': 'Track Your Order',
      '7':
      'The order can be tracked at every stage \n until it reaches you with Live Map',
      '8': 'Continue',
      '9': 'Sign In',
      '10': 'Welcome Back, ',
      '11':
      'Sign in with your Email or your Social Media Accounts',
      '12': 'Enter Your Email',
      '13': 'Enter Your Password',
      '14': 'Forgot Password?',
      '15': 'Sign In',
      '16': 'Don\'t Have An Account? ',
      '17': 'Sign Up',
      '18': 'Email',
      '19': 'Password',
      '20': 'Username',
      '21': 'Phone',
      '22': 'Enter Your Phone',
      '23': 'Enter Your Username',
      '24':
      'Sign Up with your Email or your Social Media Accounts',
      '25': 'Already have an account?, ',
      '26': 'Sign In',
      '27': 'Check Email',
      '28': 'Your account was created Successfully !',
      '29': 'Please enter your registered Email to receive a verification code',
      '30': 'Check',
      '31': 'Go To Login',
      '32': 'Success!',
      '33': 'Save',
      '34': 'Please Enter New Password',
      '35': 'New Password',
      '36': 'Password has been reset successfully',
      '37': 'Congratulations!',
      '38': 'Successfully registered!',
      '39' : 'Verification Code',
      '40' : 'Verification code has been sent',
      '41' : 'Please enter 6 digits code sent to',
      '42' : 'Forgot Password',
      '43' : 'Reset Password',
      '44' : 'Choose a strong password contains letters, numbers and symbols',
      '45' : 'Password verification',
      '46' : 'Re-Enter New Password'
    }
      };
}
